baseURL = 'https://lonnblad.github.io/blog'
languageCode = 'en-us'
title = "Fredrik's Blog"
# theme = "terminal"

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Fredrik's Blog"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Fredrik's Blog"
      logoHomeLink = "/blog"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"

[module]

[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v3'
